# Generated by Django 4.1 on 2024-07-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'NEBULOSA'), ('ESTRELA', 'ESTRELA'), ('GALÁXIA', 'GALÁXIA'), ('PLANETA', 'PLANETA')], default='', max_length=100),
        ),
    ]
