# Generated by Django 4.1 on 2024-07-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotofrafia',
            new_name='data_fotografia',
        ),
    ]
