# Generated by Django 4.1 on 2024-07-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_rename_data_fotofrafia_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicado',
            new_name='publicada',
        ),
    ]
